sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install python-coveralls coverage
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script: nosetests --with-coverage
after_success:
  - coveralls --config_file .coveragerc
notifications:
  email: false
addons:
  apt:
    packages:
      - libhidapi-dev
      - libudev-dev
      - libusb-1.0-0-dev
