sudo: false
language: python
dist: xenial
cache:
  - apt
  - pip
matrix:
  include:
    - os: linux
      python:
      - 2.7
      - 3.6
      - 3.7
      script:
      - coverage run --source toon -m pytest -v
      - coverage report
      after_success:
      - coveralls
    
    - os: osx
      language: generic
      install:
      - pip3 install -r requirements.txt
      - pip3 install -r requirements_test.txt
      - pip3 install .


install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install python-coveralls coverage
  - pip install .
notifications:
  email: false
