sudo: false
language: python
dist: xenial
cache:
  - pip
python:
  - 2.7
  - 3.6

matrix:
  include:
    - os: linux
      language: python
      python: 3.7
      after_success:
      - coveralls
    
    - os: osx
      language: generic

    # default version of python3 (3.6.5)
    - os: osx
      language: generic
      install:
      - python3 -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'
      - pip3 install -r requirements.txt
      - pip3 install -r requirements_test.txt
      - pip3 install python-coveralls coverage
      - pip3 install .


install:
  - python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install python-coveralls coverage
  - pip install .
script:
  - coverage run --source toon -m pytest -v
  - coverage report
notifications:
  email: false
