sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script: nosetests
notifications:
  email: false
addons:
  apt:
    packages:
      - libhidapi-dev
      - libudev-dev
      - libusb-1.0-0-dev
