sudo: false
language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: "aforren1"
  password:
    secure: "WW/rzt2mcJMUHopeBdZ2s5Xo7+VkORzTgxTdP9DDJRqqxcCk6tmRtxaCBciWwDQ4TDT57+1tZljq6+7KPigpoZK0Q+A483dNBj8scfugm33OCbjH7GFPoG/yG7L0U4yFp0DHooNv1wijMEwYC8bJR3QLVTu0hdIWNhZrcwPeGwp4zmvd0YQap9/T5nYRMfOvuUiEJ05Spad2yecnKbwfSCs1WRxb0VAN1xl8P3xrs8tc55td4UKJn19FMrfHkP38jQilMQ7LFBUog0G+hV+PlY4aoW7/mmhq5mcEEu5k2klX3hw9olnvhmVC1XWSbuY2C70fzEtd3cYP40nRjwO6jPf+ybsGRbDYXO6T8g1dpruLPvCPz1l7SOt6jaQOg7v2VY9hVN/Rpro1UxZ9Qtu162nYzf2vdNpygm0YC1AnB1wFltWgC2cY7BhkFX1D4rgMPfsdQmYtfMpwkZiGW37UFJGfKcITjgnOtr81xafh4hGtDOltR6ajcewrcPLjDIZHN0bhSG0NNPJFzUwIvyDAI38sQpwnG8/Koxf5e+E0P4JMcr131izROqlbRVXTAyiQw4+od8az8LFwBz1aoeG8swuxJLq0kW0bhCVPcYlmL0asBCSMhhE5Wu9Ln3k/T6McdPrK/Up5ZuLFe38LNwrzBj6eZZWbIzO/vYJaThRi0gA="
  on:
    tags: true

