sudo: false
language: python
dist: xenial
cache:
  - apt
  - pip
matrix:
  include:
    - os: linux
      python: 2.7

    - os: linux
      python: 3.6
    
    - os: linux
      python: 3.7


install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install python-coveralls coverage
  - pip install .[full]
script:
  - coverage run --source toon -m pytest -v
  - coverage report
after_success:
  - coveralls
notifications:
  email: false
addons:
  apt:
    packages:
      - libhidapi-dev
      - libudev-dev
      - libusb-1.0-0-dev
