name: Build

on: [push]

env:
  CIBW_SKIP: cp34-* cp35-* *-manylinux_i686 *-win32
  CIBW_BUILD: cp3?-*
  CIBW_TEST_COMMAND: python -m pip install toon pytest && python -m pytest {project}

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Look
      run: |
        ls wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse