name: Build

on: [push]

env:
  CIBW_SKIP: cp34-* cp35-* *-manylinux_i686 *-win32
  CIBW_BUILD: cp3?-*
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010

jobs:
  run_tests:
    name: Build and run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    
    - name: Install toon
      run: |
        python -m pip install -e .

    - name: Run tests and coveralls
      run: |
        python -m pip install coveralls && python -m pip install -r requirements_test.txt
        coverage run --source=toon -m pytest -v -s && coverage report && coveralls

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    needs: [run_tests]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.1
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Look
      run: |
        ls wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse